<?php

namespace App\Helpers;

use Illuminate\Support\Facades\Redis;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Route;

class Utils
{
    const current_nationality  = [
        'AND' =>'Andorra',
        'ARG' =>'Argentina',
        'ARM' =>'Armenia',
        'AUS' =>'Australia',
        'AUT' =>'Austria',
        'AZE' =>'Azerbaijan',
        'BLR' =>'Belarus',
        'BEL' =>'Belgium',
        'BIH' =>'Bosnia',
        'BRA' =>'Brazil',
        'BRN' =>'Bruney',
        'BGR' =>'Bulgaria',
        'CAN' =>'Canada',
        'CHL' =>'Chile',
        'CHN' =>'China',
        'COL' =>'Colombia',
        'HRV' =>'Croatia',
        'CUB' =>'Cuba',
        'CYP' =>'Cyprus',
        'CZE' =>'Czech',
        'DNK' =>'Denmark',
        'EST' =>'Estonia',
        'FJI' =>'Fiji',
        'FIN' =>'Finland',
        'FRA' =>'France',
        'GEO' =>'Georgia',
        'D' =>'Germany',
        'GRC' =>'Greece',
        'HUN' =>'Hungary',
        'ISL' =>'Iceland',
        'IND' =>'India',
        'IRL' =>'Ireland',
        'ITA' =>'Italy',
        'JPN' =>'Japan',
        'KAZ' =>'Kazakhstan',
        'KOR' =>'Korea',
        'LVA' =>'Latvia',
        'LIE' =>'Liechtenstein',
        'LTU' =>'Lithuania',
        'LUX' =>'Luxembourg',
        'MKD' =>'Macedonia',
        'MLT' =>'Malta',
        'MHL' =>'Marshall',
        'MEX' =>'Mexico',
        'FSM' =>'Micronesia',
        'MDA' =>'Moldova',
        'MCO' =>'Monaco',
        'MNG' =>'Mongolia',
        'MNE' =>'Montenegro',
        'MMR' =>'Myanmar',
        'NRU' =>'Nauru',
        'NLD' =>'Netherland',
        'NZL' =>'New',
        'NOR' =>'Norway',
        'PLW' =>'Palau',
        'PAN' =>'Panama',
        'PNG' =>'Papua',
        'PER' =>'Peru',
        'PHL' =>'Philippines',
        'POL' =>'Poland',
        'PRT' =>'Portugal',
        'QAT' =>'Qatar',
        'ROU' =>'Romania',
        'RUS' =>'Russia',
        'SMR' =>'San',
        'SRB' =>'Serbia',
        'SVK' =>'Slovakia',
        'SVN' =>'Slovenia',
        'SLB' =>'Solomon',
        'ESP' =>'Spain',
        'SWE' =>'Sweden',
        'CHE' =>'Switzerland',
        'TLS' =>'Timor',
        'ARE' =>'United',
        'GBR' =>'United',
        'USA' =>'United',
        'URY' =>'Uruguay',
        'VUT' =>'Vanuatu',
        'VEN' =>'Venezuela',
        'WSM' =>'Western'
    ];
    const passport_type  = [
        'NG' =>'Diplomatic passport',
        'CV' =>'Official passport',
        'PT' =>'Ordinary passport',
    ];
    const purpose_of_entry  = [
        '6' =>'aid activities',
        '25' =>'air crewman',
        '104' =>'ashore to the country',
        '102' =>'board the ship to return home',
        '3' =>'business activities',
        '78' =>'dealing with problem',
        '38' =>'diplomat',
        '22' =>'for volunteer',
        '59' =>'internship',
        '7' =>'investment',
        '8' =>'journalism',
        '10' =>'labor, employment',
        '89' =>'lawyer',
        '19' =>'office / orgarnization of economy, culture, technology, non-government',
        '1' =>'official visit',
        '0' =>'other',
        '82' =>'participate in sport competitions',
        '41' =>'personal / private',
        '103' =>'playing fooball',
        '12' =>'study',
        '4' =>'summit, conference',
        '90' =>'take Seagame 31',
        '101' =>'teaching',
        '69' =>'to participate Asian Physics Olympic',
        '76' =>'tourism',
        '2' =>'tourism',
        '55' =>'tourism, visiting relatives',
        '33' =>'transit travel',
        '5' =>'visiting relatives',
        '44' =>'working'
    ];
    const city_province  = [
        '805' =>'AN GIANG',
        '717' =>'BA RIA - VUNG TAU',
        '221' =>'BAC GIANG',
        '207' =>'BAC KAN',
        '821' =>'BAC LIEU',
        '223' =>'BAC NINH',
        '811' =>'BEN TRE',
        '507' =>'BINH DINH',
        '711' =>'BINH DUONG',
        '707' =>'BINH PHUOC',
        '715' =>'BINH THUAN',
        '823' =>'CA MAU',
        '815' =>'CAN THO',
        '203' =>'CAO BANG',
        '501' =>'DA NANG City',
        '605' =>'DAK LAK',
        '606' =>'DAK NONG',
        '302' =>'DIEN BIEN',
        '713' =>'DONG NAI',
        '803' =>'DONG THAP',
        '603' =>'GIA LAI',
        '201' =>'HA GIANG',
        '111' =>'HA NAM',
        '101' =>'HA NOI City',
        '405' =>'HA TINH',
        '107' =>'HAI DUONG',
        '103' =>'HAI PHONG',
        '816' =>'HAU GIANG',
        '701' =>'HO CHI MINH City',
        '305' =>'HOA BINH',
        '109' =>'HUNG YEN',
        '511' =>'KHANH HOA',
        '813' =>'KIEN GIANG',
        '601' =>'KON TUM',
        '301' =>'LAI CHAU',
        '703' =>'LAM DONG',
        '209' =>'LANG SON',
        '205' =>'LAO CAI',
        '801' =>'LONG AN',
        '113' =>'NAM DINH',
        '403' =>'NGHE AN',
        '117' =>'NINH BINH',
        '705' =>'NINH THUAN',
        '217' =>'PHU THO',
        '509' =>'PHU YEN',
        '407' =>'QUANG BINH',
        '503' =>'QUANG NAM',
        '505' =>'QUANG NGAI',
        '225' =>'QUANG NINH',
        '409' =>'QUANG TRI',
        '819' =>'SOC TRANG',
        '303' =>'SON LA',
        '709' =>'TAY NINH',
        '115' =>'THAI BINH',
        '215' =>'THAI NGUYEN',
        '401' =>'THANH HOA',
        '411' =>'THUA THIEN -HUE',
        '807' =>'TIEN GIANG',
        '817' =>'TRA VINH',
        '211' =>'TUYEN QUANG',
        '809' =>'VINH LONG',
        '219' =>'VINH PHUC',
        '213' =>'YEN BAI'
    ];
    const entry_through_checkpoint   = [
        'STS' =>'Tan Son Nhat Int Airport (Ho Chi Minh City)',
        'SPQ' =>'Phu Quoc International Airport',
        'SPB' =>'Phu Bai Int Airport',
        'SNB' =>'Noi Bai Int Airport (Ha Noi)',
        'SVD' =>'Van Don Int Airport (Quang Ninh)',
        'SCT' =>'Can Tho International Airport',
        'SCR' =>'Cam Ranh Int Airport (Khanh Hoa)',
        'SCB' =>'Cat Bi Int Airport (Hai Phong)',
        'SDN' =>'Da Nang International Airport',
        'KLB' =>'Lao Bao Landport',
        'KXM' =>'Xa Mat Landport',
        'KTR' =>'Tay Trang Landport',
        'KTB' =>'Tinh Bien Landport',
        'KST' =>'Song Tien Landport',
        'KNM' =>'Na Meo Landport',
        'KNC' =>'Nam Can Landport',
        'KMC' =>'Mong Cai Landport',
        'KMB' =>'Moc Bai Landport',
        'KLL' =>'La Lay Landport',
        'KLC' =>'Lao Cai Landport',
        'KHT' =>'Ha Tien Landport',
        'KHN' =>'Huu Nghi Landport',
        'KBY' =>'Bo Y Landport',
        'KCL' =>'Cha Lo Landport',
        'KCT' =>'Cau Treo Landport',
        'CNS' =>'Nghi Son Seaport',
        'CCM' =>'Chan May Seaport',
        'CCP' =>'Cam Pha Seaport',
        'CNT' =>'Nha Trang Seaport',
        'CDN' =>'Da Nang Seaport',
        'CDO' =>'Duong Dong Seaport',
        'CQN' =>'Quy Nhon Seaport',
        'CHG' =>'Hon Gai Seaport',
        'CHP' =>'Hai Phong Seaport',
        'CVT' =>'Vung Tau Seaport',
        'CVA' =>'Vung Ang Seaport',
        'CSG' =>'Ho Chi Minh City Seaport',
        'CDQ' =>'Dung Quat Seaport'
    ];
    public static function getRandom($length)
    {
        $token = "";
        $codeAlphabet = "0123456789";
        $max = strlen($codeAlphabet); // edited

        for ($i = 0; $i < $length; $i++) {
            $token .= $codeAlphabet[random_int(0, $max - 1)];
        }

        return $token;
    }
}
